// <auto-generated />
using System;

using Autopiter.Infrastructure;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autopiter.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240313214820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autopiter.Core.Entities.CompanyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyBranches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationName = "Тридевятое царство"
                        },
                        new
                        {
                            Id = 2,
                            LocationName = "Дремучий лес"
                        },
                        new
                        {
                            Id = 3,
                            LocationName = "Луна"
                        });
                });

            modelBuilder.Entity("Autopiter.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyBranchId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyBranchId = 1,
                            Name = "Царь"
                        },
                        new
                        {
                            Id = 2,
                            CompanyBranchId = 1,
                            Name = "Добрыня"
                        },
                        new
                        {
                            Id = 3,
                            CompanyBranchId = 2,
                            Name = "Яга"
                        },
                        new
                        {
                            Id = 4,
                            CompanyBranchId = 3,
                            Name = "Копатыч"
                        },
                        new
                        {
                            Id = 5,
                            CompanyBranchId = 3,
                            Name = "Кощей"
                        },
                        new
                        {
                            Id = 6,
                            CompanyBranchId = 3,
                            Name = "Лосяш"
                        });
                });

            modelBuilder.Entity("Autopiter.Core.Entities.Installation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("PrintingDeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("UseIndicator")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyBranchId");

                    b.HasIndex("PrintingDeviceId");

                    b.ToTable("Installations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyBranchId = 1,
                            Name = "Дворец",
                            OrderNumber = 1,
                            PrintingDeviceId = 1,
                            UseIndicator = true
                        },
                        new
                        {
                            Id = 2,
                            CompanyBranchId = 1,
                            Name = "Конюшни",
                            OrderNumber = 2,
                            PrintingDeviceId = 2,
                            UseIndicator = false
                        },
                        new
                        {
                            Id = 3,
                            CompanyBranchId = 1,
                            Name = "Оружейная",
                            OrderNumber = 3,
                            PrintingDeviceId = 2,
                            UseIndicator = false
                        },
                        new
                        {
                            Id = 4,
                            CompanyBranchId = 3,
                            Name = "Кратер",
                            OrderNumber = 1,
                            PrintingDeviceId = 3,
                            UseIndicator = true
                        },
                        new
                        {
                            Id = 5,
                            CompanyBranchId = 2,
                            Name = "Избушка",
                            OrderNumber = 3,
                            PrintingDeviceId = 2,
                            UseIndicator = false
                        },
                        new
                        {
                            Id = 6,
                            CompanyBranchId = 2,
                            Name = "Топи",
                            OrderNumber = 2,
                            PrintingDeviceId = 1,
                            UseIndicator = true
                        });
                });

            modelBuilder.Entity("Autopiter.Core.Entities.PrintingDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int");

                    b.Property<string>("MacAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrintDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionType = 0,
                            Name = "Папирус"
                        },
                        new
                        {
                            Id = 2,
                            ConnectionType = 0,
                            Name = "Бумага"
                        },
                        new
                        {
                            Id = 3,
                            ConnectionType = 1,
                            Name = "Камень"
                        });
                });

            modelBuilder.Entity("Autopiter.Core.Entities.Employee", b =>
                {
                    b.HasOne("Autopiter.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyBranch");
                });

            modelBuilder.Entity("Autopiter.Core.Entities.Installation", b =>
                {
                    b.HasOne("Autopiter.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany()
                        .HasForeignKey("CompanyBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autopiter.Core.Entities.PrintingDevice", "PrintingDevice")
                        .WithMany()
                        .HasForeignKey("PrintingDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyBranch");

                    b.Navigation("PrintingDevice");
                });

            modelBuilder.Entity("Autopiter.Core.Entities.CompanyBranch", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
